first_name = "John"
last_name = "Doe"
email_name = "example"
email_domain = "gmail.com"
password = "password" # Optional
address = "303 2nd St, Suite 800 San Francisco"
quantity = 5
headless = true # Optional